### ISSUE TITLE
Better error handling on OAuth/Lite2/Client/WebServer.pm

### ISSUE THREAD

**Issue by tokuhirom** [lyokato/p5-oauth-lite2#4]
OAuth::Lite2::Client::WebServer->get_access_token returns error message only on the error, but in some case, i want to see the HTTP response object directly.

**Comment by lyokato** [comment]
added last_request and last_response methods on client classes.
Released as OAuth-Lite2-0.01_07.

(And also without these methods, you can see dumped HTTP::Response
with OAuth::Lite::Agent::Dump.)
